### ISSUE TITLE
Not able to put up multi line response in rasa x demo conversational bot

### ISSUE THREAD

**Issue by umangnangal** [RasaHQ/rasa-x-demo#27]
The domain.yml file is modified resulting in removing extra line in the content when rasa x is run.
I am not seeing a clean way of adding a multi line response.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @degiz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by degiz** [comment]
Hey @umangnangal 

Could you please give an example of your `domain.yml`?

**Comment by umangnangal** [comment]
This is one of the utter response in domain.yml
I wanted each line to be printed after one another, like an ordered list. But I am not able to do that.
Even if I make the changes, after running rasa x, the domain.yml gets realigned and all the extra spaces are stripped.

utter_core_debug:
  - text: 'Steps to debug a core dump \ 1. run bash sudo su \ 2. cd /logflash/core
      \ 3. ls | grep <core pid> \ 4. tar xvzf core.tar.gz \ 5. gunzip core.gz \ 6.
      gdb /isan/bin/<process> <process_core> \ 7. bt \ '

**Comment by degiz** [comment]
Thanks @umangnangal 
We'll address that in the other issue.
