### ISSUE TITLE
Enhancement : Python script to convert IBM Watson Assistant Training Data in csv format into RASA expected training data markdown format.

### ISSUE THREAD

**Issue by umangnangal** [RasaHQ/rasa-x-demo#28]
Hi Team,
I have written a cool script which can be used to convert IBM Watson Training Data into RASA defined format.
Recently, I shifted from IBM to RASA for my Chatbot requirement and came across this challenge.
I would like to contribute the script into the project.
Please let me know if we have a directory containing similar scripts which provides an easy way to port customers from other platforms easily. I would be happy to contribute for the IBM watson part :)

**Comment by sara-tagger** [comment]
Thanks for the issue, @melindaloubser1 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
Hi @umangnangal , that sounds useful! This is something that would live on the `rasa` repo. Take a look at e.g. this migration doc for dialogflow: https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/. You probably noticed that the IBM Watson page doesn't yet have a migration method, is that what you wanted to add? If so, please do open an issue &  linked PR on the Rasa  repo and feel free to tag me in it.

**Comment by umangnangal** [comment]
Yes @melindaloubser1 , you got it right. I am currently writing the code for enhancement.
Will raise a issue on the rasa repo and tag you. Thanks 🙂.
